'use strict';

// Question bank for Duel Trivia.
// `correct` is the index into `choices` in this source file only —
// the server re-shuffles choices at serve time and never sends the index
// to clients before the reveal.

module.exports = [
  // ── Ukraine (20) ────────────────────────────────────────────────
  { id: 'ua-01', category: 'Ukraine', difficulty: 'easy',
    text: 'What is the capital of Ukraine?',
    choices: ['Kyiv', 'Lviv', 'Odesa', 'Kharkiv'], correct: 0 },
  { id: 'ua-02', category: 'Ukraine', difficulty: 'easy',
    text: 'Which is the longest river flowing through Ukraine?',
    choices: ['Dnipro', 'Danube', 'Dnister', 'Volga'], correct: 0 },
  { id: 'ua-03', category: 'Ukraine', difficulty: 'easy',
    text: 'Borshch, a dish closely associated with Ukraine, is a soup made primarily with which vegetable?',
    choices: ['Beetroot', 'Pumpkin', 'Zucchini', 'Spinach'], correct: 0 },
  { id: 'ua-04', category: 'Ukraine', difficulty: 'easy',
    text: 'What is a vyshyvanka?',
    choices: ['An embroidered traditional shirt', 'A folk dance', 'A wooden flute', 'A straw hat'], correct: 0 },
  { id: 'ua-05', category: 'Ukraine', difficulty: 'easy',
    text: 'What is the currency of Ukraine?',
    choices: ['Hryvnia', 'Zloty', 'Ruble', 'Lev'], correct: 0 },
  { id: 'ua-06', category: 'Ukraine', difficulty: 'easy',
    text: 'Which sea lies along the southern coast of Ukraine?',
    choices: ['Black Sea', 'Baltic Sea', 'Caspian Sea', 'Adriatic Sea'], correct: 0 },
  { id: 'ua-07', category: 'Ukraine', difficulty: 'easy',
    text: 'Which mountain range stretches across western Ukraine?',
    choices: ['Carpathians', 'Alps', 'Urals', 'Pyrenees'], correct: 0 },
  { id: 'ua-08', category: 'Ukraine', difficulty: 'easy',
    text: 'Which western Ukrainian city is famous for its coffeehouse culture and lion statues?',
    choices: ['Lviv', 'Poltava', 'Zaporizhzhia', 'Mykolaiv'], correct: 0 },
  { id: 'ua-09', category: 'Ukraine', difficulty: 'medium',
    text: 'What is the highest peak in Ukraine?',
    choices: ['Hoverla', 'Elbrus', 'Gerlach', 'Musala'], correct: 0 },
  { id: 'ua-10', category: 'Ukraine', difficulty: 'easy',
    text: 'Varenyky are Ukrainian dumplings often filled with potato or which fruit?',
    choices: ['Sour cherries', 'Bananas', 'Oranges', 'Kiwi'], correct: 0 },
  { id: 'ua-11', category: 'Ukraine', difficulty: 'medium',
    text: 'What is the Ukrainian dish holubtsi?',
    choices: ['Stuffed cabbage rolls', 'A fish soup', 'A honey cake', 'Fried cheese pancakes'], correct: 0 },
  { id: 'ua-12', category: 'Ukraine', difficulty: 'medium',
    text: 'Which many-stringed instrument is a national symbol of Ukrainian folk music?',
    choices: ['Bandura', 'Balalaika', 'Sitar', 'Banjo'], correct: 0 },
  { id: 'ua-13', category: 'Ukraine', difficulty: 'medium',
    text: 'Kutia, a traditional Ukrainian Christmas dish, is made from wheat, honey and what else?',
    choices: ['Poppy seeds', 'Minced beef', 'Pickled herring', 'Melted cheese'], correct: 0 },
  { id: 'ua-14', category: 'Ukraine', difficulty: 'medium',
    text: 'According to legend, Kyiv was founded by three brothers and their sister. What was the eldest brother’s name?',
    choices: ['Kyi', 'Bohdan', 'Taras', 'Danylo'], correct: 0 },
  { id: 'ua-15', category: 'Ukraine', difficulty: 'easy',
    text: 'In which year did the Chornobyl nuclear disaster occur?',
    choices: ['1986', '1979', '1991', '1968'], correct: 0 },
  { id: 'ua-16', category: 'Ukraine', difficulty: 'medium',
    text: 'The famous Potemkin Stairs are a landmark of which Ukrainian city?',
    choices: ['Odesa', 'Kyiv', 'Chernihiv', 'Uzhhorod'], correct: 0 },
  { id: 'ua-17', category: 'Ukraine', difficulty: 'medium',
    text: 'Which Ukrainian poet wrote the celebrated collection “Kobzar”?',
    choices: ['Taras Shevchenko', 'Ivan Franko', 'Lesya Ukrainka', 'Hryhorii Skovoroda'], correct: 0 },
  { id: 'ua-18', category: 'Ukraine', difficulty: 'medium',
    text: 'What are pysanky?',
    choices: ['Decorated Easter eggs', 'Embroidered towels', 'Clay whistles', 'Woven belts'], correct: 0 },
  { id: 'ua-19', category: 'Ukraine', difficulty: 'easy',
    text: 'Which of these countries shares a border with Ukraine?',
    choices: ['Poland', 'Lithuania', 'Bulgaria', 'Latvia'], correct: 0 },
  { id: 'ua-20', category: 'Ukraine', difficulty: 'easy',
    text: 'Salo, a beloved Ukrainian delicacy, is made from what?',
    choices: ['Cured pork fat', 'Smoked salmon', 'Goat cheese', 'Dried mushrooms'], correct: 0 },

  // ── Czech Republic (20) ─────────────────────────────────────────
  { id: 'cz-01', category: 'Czech Republic', difficulty: 'easy',
    text: 'What is the capital of the Czech Republic?',
    choices: ['Prague', 'Brno', 'Ostrava', 'Plzeň'], correct: 0 },
  { id: 'cz-02', category: 'Czech Republic', difficulty: 'easy',
    text: 'Which famous medieval bridge crosses the Vltava river in Prague?',
    choices: ['Charles Bridge', 'Tower Bridge', 'Rialto Bridge', 'Chain Bridge'], correct: 0 },
  { id: 'cz-03', category: 'Czech Republic', difficulty: 'easy',
    text: 'Pilsner Urquell, the original pale lager, comes from which Czech city?',
    choices: ['Plzeň', 'Olomouc', 'Liberec', 'Karlovy Vary'], correct: 0 },
  { id: 'cz-04', category: 'Czech Republic', difficulty: 'easy',
    text: 'Škoda, one of the world’s oldest car makers, is from which country?',
    choices: ['Czech Republic', 'Germany', 'Sweden', 'France'], correct: 0 },
  { id: 'cz-05', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which playwright and former dissident became the first president of the Czech Republic?',
    choices: ['Václav Havel', 'Václav Klaus', 'Alexander Dubček', 'Miloš Zeman'], correct: 0 },
  { id: 'cz-06', category: 'Czech Republic', difficulty: 'easy',
    text: 'Krtek, the beloved Czech cartoon character, is what kind of animal?',
    choices: ['A mole', 'A hedgehog', 'A rabbit', 'A badger'], correct: 0 },
  { id: 'cz-07', category: 'Czech Republic', difficulty: 'medium',
    text: 'Charles IV, King of Bohemia and Holy Roman Emperor, founded what in Prague in 1348?',
    choices: ['A university', 'An opera house', 'A brewery', 'A zoo'], correct: 0 },
  { id: 'cz-08', category: 'Czech Republic', difficulty: 'easy',
    text: 'What is the currency of the Czech Republic?',
    choices: ['Czech koruna', 'Euro', 'Forint', 'Franc'], correct: 0 },
  { id: 'cz-09', category: 'Czech Republic', difficulty: 'medium',
    text: 'What is the Orloj, a famous attraction on Prague’s Old Town Square?',
    choices: ['A medieval astronomical clock', 'A golden fountain', 'A marionette theatre', 'A bell tower organ'], correct: 0 },
  { id: 'cz-10', category: 'Czech Republic', difficulty: 'medium',
    text: 'In which sport did the Czech Republic win Olympic gold at Nagano 1998, sparking national celebrations?',
    choices: ['Ice hockey', 'Football', 'Basketball', 'Volleyball'], correct: 0 },
  { id: 'cz-11', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which Czech composer wrote “Vltava”, part of the cycle “Má vlast” (My Homeland)?',
    choices: ['Bedřich Smetana', 'Antonín Dvořák', 'Leoš Janáček', 'Bohuslav Martinů'], correct: 0 },
  { id: 'cz-12', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which Czech composer wrote the “New World Symphony” while living in America?',
    choices: ['Antonín Dvořák', 'Bedřich Smetana', 'Franz Liszt', 'Gustav Mahler'], correct: 0 },
  { id: 'cz-13', category: 'Czech Republic', difficulty: 'easy',
    text: 'Which author of “The Metamorphosis” was born in Prague in 1883?',
    choices: ['Franz Kafka', 'Milan Kundera', 'Stefan Zweig', 'Hermann Hesse'], correct: 0 },
  { id: 'cz-14', category: 'Czech Republic', difficulty: 'medium',
    text: 'The word “robot” was introduced to the world in a 1920 play by which Czech writer?',
    choices: ['Karel Čapek', 'Jaroslav Hašek', 'Božena Němcová', 'Franz Kafka'], correct: 0 },
  { id: 'cz-15', category: 'Czech Republic', difficulty: 'easy',
    text: 'What is the name of the historical region in the eastern part of the Czech Republic?',
    choices: ['Moravia', 'Bavaria', 'Silesia Major', 'Galicia'], correct: 0 },
  { id: 'cz-16', category: 'Czech Republic', difficulty: 'medium',
    text: 'In which year did Czechoslovakia peacefully split into the Czech Republic and Slovakia?',
    choices: ['1993', '1989', '1997', '1985'], correct: 0 },
  { id: 'cz-17', category: 'Czech Republic', difficulty: 'easy',
    text: 'The classic Czech dish “vepřo knedlo zelo” consists of roast pork, cabbage and what else?',
    choices: ['Bread dumplings', 'French fries', 'Rice', 'Spaghetti'], correct: 0 },
  { id: 'cz-18', category: 'Czech Republic', difficulty: 'medium',
    text: 'Prague Castle holds a Guinness World Record as the largest what?',
    choices: ['Ancient castle complex', 'Wooden building', 'Underground labyrinth', 'Royal garden'], correct: 0 },
  { id: 'cz-19', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which Czech town is world-famous for its hot springs and spa colonnades?',
    choices: ['Karlovy Vary', 'Kutná Hora', 'Telč', 'České Budějovice'], correct: 0 },
  { id: 'cz-20', category: 'Czech Republic', difficulty: 'easy',
    text: 'The Czech Republic has long held the world record in the per-capita consumption of what?',
    choices: ['Beer', 'Coffee', 'Chocolate', 'Ice cream'], correct: 0 },

  // ── Video games (20) ────────────────────────────────────────────
  { id: 'vg-01', category: 'Video games', difficulty: 'easy',
    text: 'In which country was Tetris created in 1984?',
    choices: ['Soviet Union', 'Japan', 'United States', 'Germany'], correct: 0 },
  { id: 'vg-02', category: 'Video games', difficulty: 'easy',
    text: 'What is the profession of Nintendo’s mascot Mario?',
    choices: ['Plumber', 'Carpenter', 'Chef', 'Firefighter'], correct: 0 },
  { id: 'vg-03', category: 'Video games', difficulty: 'easy',
    text: 'What is the name of Mario’s taller, green-clad brother?',
    choices: ['Luigi', 'Wario', 'Yoshi', 'Toad'], correct: 0 },
  { id: 'vg-04', category: 'Video games', difficulty: 'easy',
    text: 'What is the name of the hero you play in “The Legend of Zelda” games?',
    choices: ['Link', 'Zelda', 'Ganon', 'Epona'], correct: 0 },
  { id: 'vg-05', category: 'Video games', difficulty: 'easy',
    text: 'Which studio originally created Minecraft?',
    choices: ['Mojang', 'Ubisoft', 'Valve', 'Blizzard'], correct: 0 },
  { id: 'vg-06', category: 'Video games', difficulty: 'medium',
    text: 'The Witcher games are based on books by an author from which country?',
    choices: ['Poland', 'Russia', 'Czech Republic', 'Hungary'], correct: 0 },
  { id: 'vg-07', category: 'Video games', difficulty: 'easy',
    text: 'What is the name of the monster-slaying protagonist of The Witcher series?',
    choices: ['Geralt of Rivia', 'Ezio Auditore', 'Arthas Menethil', 'Triss Merigold'], correct: 0 },
  { id: 'vg-08', category: 'Video games', difficulty: 'medium',
    text: 'The game Kingdom Come: Deliverance is set in the medieval kingdom of…',
    choices: ['Bohemia', 'Burgundy', 'Castile', 'Wessex'], correct: 0 },
  { id: 'vg-09', category: 'Video games', difficulty: 'medium',
    text: 'Which studio created the pioneering shooter Doom in 1993?',
    choices: ['id Software', 'Epic Games', 'Rockstar', 'Naughty Dog'], correct: 0 },
  { id: 'vg-10', category: 'Video games', difficulty: 'easy',
    text: 'Pac-Man, the dot-munching arcade classic, was originally released by a company from which country?',
    choices: ['Japan', 'United States', 'South Korea', 'Italy'], correct: 0 },
  { id: 'vg-11', category: 'Video games', difficulty: 'easy',
    text: 'Sega’s speedy blue mascot Sonic is what kind of animal?',
    choices: ['Hedgehog', 'Fox', 'Armadillo', 'Porcupine'], correct: 0 },
  { id: 'vg-12', category: 'Video games', difficulty: 'easy',
    text: 'In Pokémon, what type is Pikachu?',
    choices: ['Electric', 'Fire', 'Water', 'Grass'], correct: 0 },
  { id: 'vg-13', category: 'Video games', difficulty: 'easy',
    text: 'What does GTA stand for in the famous game series?',
    choices: ['Grand Theft Auto', 'Great Tank Assault', 'Global Tactical Army', 'Grand Turbo Arena'], correct: 0 },
  { id: 'vg-14', category: 'Video games', difficulty: 'easy',
    text: 'Which hybrid home/portable console did Nintendo release in 2017?',
    choices: ['Switch', 'Wii U', 'GameCube', 'Dreamcast'], correct: 0 },
  { id: 'vg-15', category: 'Video games', difficulty: 'medium',
    text: 'In the game Portal, which reward is famously promised — and famously “a lie”?',
    choices: ['Cake', 'Pizza', 'A gold medal', 'A vacation'], correct: 0 },
  { id: 'vg-16', category: 'Video games', difficulty: 'easy',
    text: 'Which company created Fortnite?',
    choices: ['Epic Games', 'Activision', 'EA', 'Riot Games'], correct: 0 },
  { id: 'vg-17', category: 'Video games', difficulty: 'medium',
    text: 'Master Chief is the armored hero of which game series?',
    choices: ['Halo', 'Gears of War', 'Destiny', 'Mass Effect'], correct: 0 },
  { id: 'vg-18', category: 'Video games', difficulty: 'easy',
    text: 'Lara Croft is the adventuring star of which game series?',
    choices: ['Tomb Raider', 'Uncharted', 'Far Cry', 'Resident Evil'], correct: 0 },
  { id: 'vg-19', category: 'Video games', difficulty: 'medium',
    text: 'Kingdom Come: Deliverance was developed by Warhorse Studios, based in which city?',
    choices: ['Prague', 'Warsaw', 'Berlin', 'Vienna'], correct: 0 },
  { id: 'vg-20', category: 'Video games', difficulty: 'medium',
    text: 'Rovio, the company behind Angry Birds, comes from which country?',
    choices: ['Finland', 'Japan', 'Canada', 'Ireland'], correct: 0 },

  // ── Movies & TV (25) ────────────────────────────────────────────
  { id: 'mv-01', category: 'Movies & TV', difficulty: 'easy',
    text: 'Who directed the 1997 blockbuster Titanic?',
    choices: ['James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Peter Jackson'], correct: 0 },
  { id: 'mv-02', category: 'Movies & TV', difficulty: 'easy',
    text: '“May the Force be with you” is a famous line from which film saga?',
    choices: ['Star Wars', 'Star Trek', 'Dune', 'The Matrix'], correct: 0 },
  { id: 'mv-03', category: 'Movies & TV', difficulty: 'easy',
    text: 'In the sitcom Friends, what is the name of the coffee shop where the gang hangs out?',
    choices: ['Central Perk', 'The Daily Grind', 'Java Joe’s', 'MacLaren’s'], correct: 0 },
  { id: 'mv-04', category: 'Movies & TV', difficulty: 'easy',
    text: 'What is the name of the school for wizards in Harry Potter?',
    choices: ['Hogwarts', 'Durmstrang', 'Narnia', 'Rivendell'], correct: 0 },
  { id: 'mv-05', category: 'Movies & TV', difficulty: 'easy',
    text: 'In which town do The Simpsons live?',
    choices: ['Springfield', 'Quahog', 'South Park', 'Bedrock'], correct: 0 },
  { id: 'mv-06', category: 'Movies & TV', difficulty: 'easy',
    text: 'Who directed Jurassic Park (1993)?',
    choices: ['Steven Spielberg', 'George Lucas', 'Tim Burton', 'Christopher Nolan'], correct: 0 },
  { id: 'mv-07', category: 'Movies & TV', difficulty: 'easy',
    text: 'In The Matrix, which pill does Neo take to learn the truth?',
    choices: ['The red pill', 'The blue pill', 'The green pill', 'The white pill'], correct: 0 },
  { id: 'mv-08', category: 'Movies & TV', difficulty: 'easy',
    text: 'Toy Story (1995) was the first feature film made by which animation studio?',
    choices: ['Pixar', 'DreamWorks', 'Studio Ghibli', 'Illumination'], correct: 0 },
  { id: 'mv-09', category: 'Movies & TV', difficulty: 'easy',
    text: 'In Breaking Bad, what subject does Walter White teach before turning to crime?',
    choices: ['Chemistry', 'Physics', 'Mathematics', 'History'], correct: 0 },
  { id: 'mv-10', category: 'Movies & TV', difficulty: 'easy',
    text: 'Game of Thrones is based on novels by which author?',
    choices: ['George R. R. Martin', 'J. R. R. Tolkien', 'Stephen King', 'C. S. Lewis'], correct: 0 },
  { id: 'mv-11', category: 'Movies & TV', difficulty: 'easy',
    text: 'Who played the title role in Forrest Gump?',
    choices: ['Tom Hanks', 'Brad Pitt', 'Kevin Costner', 'Robin Williams'], correct: 0 },
  { id: 'mv-12', category: 'Movies & TV', difficulty: 'easy',
    text: 'What is the name of the villainous uncle in The Lion King?',
    choices: ['Scar', 'Mufasa', 'Timon', 'Rafiki'], correct: 0 },
  { id: 'mv-13', category: 'Movies & TV', difficulty: 'easy',
    text: 'In The Lord of the Rings, where must the One Ring be destroyed?',
    choices: ['Mount Doom', 'Helm’s Deep', 'Minas Tirith', 'The Shire'], correct: 0 },
  { id: 'mv-14', category: 'Movies & TV', difficulty: 'easy',
    text: 'What kind of creature is Shrek?',
    choices: ['An ogre', 'A troll', 'A giant', 'A goblin'], correct: 0 },
  { id: 'mv-15', category: 'Movies & TV', difficulty: 'medium',
    text: 'In Stranger Things, what is the sinister parallel dimension called?',
    choices: ['The Upside Down', 'The Nether', 'The Shadowlands', 'The Void'], correct: 0 },
  { id: 'mv-16', category: 'Movies & TV', difficulty: 'medium',
    text: 'In the US version of The Office, what does Dunder Mifflin sell?',
    choices: ['Paper', 'Insurance', 'Furniture', 'Printers only'], correct: 0 },
  { id: 'mv-17', category: 'Movies & TV', difficulty: 'easy',
    text: 'Which song does Elsa sing as she builds her ice palace in Frozen?',
    choices: ['Let It Go', 'Into the Unknown', 'A Whole New World', 'Under the Sea'], correct: 0 },
  { id: 'mv-18', category: 'Movies & TV', difficulty: 'medium',
    text: 'Who directed Pulp Fiction (1994)?',
    choices: ['Quentin Tarantino', 'Martin Scorsese', 'David Fincher', 'Guy Ritchie'], correct: 0 },
  { id: 'mv-19', category: 'Movies & TV', difficulty: 'easy',
    text: 'Which actor delivers the famous line “I’ll be back” in The Terminator?',
    choices: ['Arnold Schwarzenegger', 'Sylvester Stallone', 'Bruce Willis', 'Jean-Claude Van Damme'], correct: 0 },
  { id: 'mv-20', category: 'Movies & TV', difficulty: 'medium',
    text: 'In James Cameron’s Avatar (2009), what is the name of the alien moon where the story takes place?',
    choices: ['Pandora', 'Krypton', 'Arrakis', 'Endor'], correct: 0 },
  { id: 'mv-21', category: 'Movies & TV', difficulty: 'medium',
    text: 'At which London address does Sherlock Holmes famously live?',
    choices: ['221B Baker Street', '10 Downing Street', '4 Privet Drive', '42 Wallaby Way'], correct: 0 },
  { id: 'mv-22', category: 'Movies & TV', difficulty: 'easy',
    text: 'In The Big Bang Theory, which character is known for the catchphrase “Bazinga!”?',
    choices: ['Sheldon', 'Leonard', 'Howard', 'Raj'], correct: 0 },
  { id: 'mv-23', category: 'Movies & TV', difficulty: 'easy',
    text: 'In Finding Nemo, what kind of fish are Nemo and his dad Marlin?',
    choices: ['Clownfish', 'Angelfish', 'Swordfish', 'Pufferfish'], correct: 0 },
  { id: 'mv-24', category: 'Movies & TV', difficulty: 'medium',
    text: 'Which car is turned into a time machine in Back to the Future?',
    choices: ['DeLorean', 'Ford Mustang', 'Volkswagen Beetle', 'Chevrolet Camaro'], correct: 0 },
  { id: 'mv-25', category: 'Movies & TV', difficulty: 'easy',
    text: 'What is the first name of the boy left behind in Home Alone?',
    choices: ['Kevin', 'Michael', 'Timmy', 'Josh'], correct: 0 },

  // ── Fun facts (20) ──────────────────────────────────────────────
  { id: 'ff-01', category: 'Fun facts', difficulty: 'medium',
    text: 'How many hearts does an octopus have?',
    choices: ['Three', 'One', 'Two', 'Five'], correct: 0 },
  { id: 'ff-02', category: 'Fun facts', difficulty: 'easy',
    text: 'Which food never spoils when stored properly — edible even after thousands of years?',
    choices: ['Honey', 'Milk', 'Bread', 'Cheese'], correct: 0 },
  { id: 'ff-03', category: 'Fun facts', difficulty: 'medium',
    text: 'How many bones are in the adult human body?',
    choices: ['206', '186', '250', '300'], correct: 0 },
  { id: 'ff-04', category: 'Fun facts', difficulty: 'easy',
    text: 'What is the fastest land animal?',
    choices: ['Cheetah', 'Lion', 'Pronghorn', 'Greyhound'], correct: 0 },
  { id: 'ff-05', category: 'Fun facts', difficulty: 'easy',
    text: 'What is the largest animal ever known to have lived on Earth?',
    choices: ['Blue whale', 'African elephant', 'Tyrannosaurus rex', 'Giant squid'], correct: 0 },
  { id: 'ff-06', category: 'Fun facts', difficulty: 'medium',
    text: 'Botanically speaking, the banana plant is classified as what?',
    choices: ['An herb', 'A tree', 'A shrub', 'A vine'], correct: 0 },
  { id: 'ff-07', category: 'Fun facts', difficulty: 'easy',
    text: 'What is a group of lions called?',
    choices: ['A pride', 'A pack', 'A herd', 'A flock'], correct: 0 },
  { id: 'ff-08', category: 'Fun facts', difficulty: 'medium',
    text: 'Which animal can sleep for up to 22 hours a day?',
    choices: ['Koala', 'Horse', 'Dolphin', 'Cheetah'], correct: 0 },
  { id: 'ff-09', category: 'Fun facts', difficulty: 'medium',
    text: 'Which element makes up the largest share of the human body by mass?',
    choices: ['Oxygen', 'Carbon', 'Iron', 'Calcium'], correct: 0 },
  { id: 'ff-10', category: 'Fun facts', difficulty: 'medium',
    text: 'The shortest war in recorded history, between Britain and Zanzibar in 1896, lasted roughly how long?',
    choices: ['40 minutes', '4 hours', '4 days', '4 weeks'], correct: 0 },
  { id: 'ff-11', category: 'Fun facts', difficulty: 'easy',
    text: 'Which bird lays the largest egg of any living animal?',
    choices: ['Ostrich', 'Emu', 'Albatross', 'Swan'], correct: 0 },
  { id: 'ff-12', category: 'Fun facts', difficulty: 'medium',
    text: 'Before the 17th century, most cultivated carrots were what colour?',
    choices: ['Purple', 'Orange', 'Blue', 'Pink'], correct: 0 },
  { id: 'ff-13', category: 'Fun facts', difficulty: 'medium',
    text: 'What is a group of cats called?',
    choices: ['A clowder', 'A litter', 'A colony wave', 'A purr'], correct: 0 },
  { id: 'ff-14', category: 'Fun facts', difficulty: 'easy',
    text: 'What is the only mammal capable of true, sustained flight?',
    choices: ['Bat', 'Flying squirrel', 'Sugar glider', 'Colugo'], correct: 0 },
  { id: 'ff-15', category: 'Fun facts', difficulty: 'easy',
    text: 'Which fruit wears its seeds on the outside?',
    choices: ['Strawberry', 'Raspberry', 'Blueberry', 'Grape'], correct: 0 },
  { id: 'ff-16', category: 'Fun facts', difficulty: 'medium',
    text: 'The spiciness of chili peppers is measured on which scale?',
    choices: ['Scoville scale', 'Richter scale', 'Beaufort scale', 'Mohs scale'], correct: 0 },
  { id: 'ff-17', category: 'Fun facts', difficulty: 'easy',
    text: 'In which hemisphere do nearly all wild penguins live?',
    choices: ['Southern', 'Northern', 'Both equally', 'Only at the equator'], correct: 0 },
  { id: 'ff-18', category: 'Fun facts', difficulty: 'easy',
    text: 'How many teeth does an adult human typically have, including wisdom teeth?',
    choices: ['32', '28', '36', '24'], correct: 0 },
  { id: 'ff-19', category: 'Fun facts', difficulty: 'medium',
    text: 'How many neck vertebrae does a giraffe have?',
    choices: ['Seven — the same as humans', 'Fourteen', 'Twenty-one', 'Three'], correct: 0 },
  { id: 'ff-20', category: 'Fun facts', difficulty: 'easy',
    text: 'Which animal is famously the slowest-moving mammal on Earth?',
    choices: ['Three-toed sloth', 'Tortoise', 'Snail', 'Koala'], correct: 0 },

  // ── Science & space (15) ────────────────────────────────────────
  { id: 'sc-01', category: 'Science & space', difficulty: 'easy',
    text: 'Which planet is known as the Red Planet?',
    choices: ['Mars', 'Venus', 'Jupiter', 'Mercury'], correct: 0 },
  { id: 'sc-02', category: 'Science & space', difficulty: 'easy',
    text: 'What is the largest planet in our solar system?',
    choices: ['Jupiter', 'Saturn', 'Neptune', 'Earth'], correct: 0 },
  { id: 'sc-03', category: 'Science & space', difficulty: 'easy',
    text: 'Which element has the chemical symbol O?',
    choices: ['Oxygen', 'Osmium', 'Gold', 'Oxide'], correct: 0 },
  { id: 'sc-04', category: 'Science & space', difficulty: 'easy',
    text: 'H₂O is the chemical formula for what?',
    choices: ['Water', 'Hydrogen peroxide', 'Salt', 'Ozone'], correct: 0 },
  { id: 'sc-05', category: 'Science & space', difficulty: 'easy',
    text: 'Who was the first human to travel into space, in 1961?',
    choices: ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn'], correct: 0 },
  { id: 'sc-06', category: 'Science & space', difficulty: 'easy',
    text: 'Who was the first person to walk on the Moon?',
    choices: ['Neil Armstrong', 'Yuri Gagarin', 'Michael Collins', 'Alan Shepard'], correct: 0 },
  { id: 'sc-07', category: 'Science & space', difficulty: 'medium',
    text: 'What is the approximate speed of light in a vacuum?',
    choices: ['300,000 km per second', '30,000 km per second', '3,000 km per second', '3 million km per second'], correct: 0 },
  { id: 'sc-08', category: 'Science & space', difficulty: 'easy',
    text: 'Which planet is famous for its spectacular ring system?',
    choices: ['Saturn', 'Mars', 'Mercury', 'Venus'], correct: 0 },
  { id: 'sc-09', category: 'Science & space', difficulty: 'medium',
    text: 'Who discovered penicillin in 1928?',
    choices: ['Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Robert Koch'], correct: 0 },
  { id: 'sc-10', category: 'Science & space', difficulty: 'easy',
    text: 'Who developed the theory of relativity?',
    choices: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Stephen Hawking'], correct: 0 },
  { id: 'sc-11', category: 'Science & space', difficulty: 'medium',
    text: 'Which element has the chemical symbol Au?',
    choices: ['Gold', 'Silver', 'Aluminium', 'Argon'], correct: 0 },
  { id: 'sc-12', category: 'Science & space', difficulty: 'easy',
    text: 'What is the closest star to Earth?',
    choices: ['The Sun', 'Proxima Centauri', 'Sirius', 'Polaris'], correct: 0 },
  { id: 'sc-13', category: 'Science & space', difficulty: 'easy',
    text: 'How many planets are in our solar system?',
    choices: ['Eight', 'Nine', 'Seven', 'Ten'], correct: 0 },
  { id: 'sc-14', category: 'Science & space', difficulty: 'medium',
    text: 'Marie Curie won Nobel Prizes in which two sciences?',
    choices: ['Physics and Chemistry', 'Physics and Medicine', 'Chemistry and Medicine', 'Physics and Literature'], correct: 0 },
  { id: 'sc-15', category: 'Science & space', difficulty: 'easy',
    text: 'What shape is the DNA molecule?',
    choices: ['Double helix', 'Single ring', 'Flat sheet', 'Triple knot'], correct: 0 },
];
