'use strict';

// Question bank for Duel Trivia.
// `correct` is the index into `choices` in this source file only —
// the server re-shuffles choices at serve time and never sends the index
// to clients before the reveal.

module.exports = [
  // ── Ukraine (20) ────────────────────────────────────────────────
  { id: 'ua-01', category: 'Ukraine', difficulty: 'easy',
    text: 'What is the capital of Ukraine?',
    choices: ['Kyiv', 'Lviv', 'Odesa', 'Kharkiv'], correct: 0 },
  { id: 'ua-02', category: 'Ukraine', difficulty: 'easy',
    text: 'Which is the longest river flowing through Ukraine?',
    choices: ['Dnipro', 'Danube', 'Dnister', 'Volga'], correct: 0 },
  { id: 'ua-03', category: 'Ukraine', difficulty: 'easy',
    text: 'Borshch, a dish closely associated with Ukraine, is a soup made primarily with which vegetable?',
    choices: ['Beetroot', 'Pumpkin', 'Zucchini', 'Spinach'], correct: 0 },
  { id: 'ua-04', category: 'Ukraine', difficulty: 'easy',
    text: 'What is a vyshyvanka?',
    choices: ['An embroidered traditional shirt', 'A folk dance', 'A wooden flute', 'A straw hat'], correct: 0 },
  { id: 'ua-05', category: 'Ukraine', difficulty: 'easy',
    text: 'What is the currency of Ukraine?',
    choices: ['Hryvnia', 'Zloty', 'Ruble', 'Lev'], correct: 0 },
  { id: 'ua-06', category: 'Ukraine', difficulty: 'easy',
    text: 'Which sea lies along the southern coast of Ukraine?',
    choices: ['Black Sea', 'Baltic Sea', 'Caspian Sea', 'Adriatic Sea'], correct: 0 },
  { id: 'ua-07', category: 'Ukraine', difficulty: 'easy',
    text: 'Which mountain range stretches across western Ukraine?',
    choices: ['Carpathians', 'Alps', 'Urals', 'Pyrenees'], correct: 0 },
  { id: 'ua-08', category: 'Ukraine', difficulty: 'easy',
    text: 'Which western Ukrainian city is famous for its coffeehouse culture and lion statues?',
    choices: ['Lviv', 'Poltava', 'Zaporizhzhia', 'Mykolaiv'], correct: 0 },
  { id: 'ua-09', category: 'Ukraine', difficulty: 'medium',
    text: 'What is the highest peak in Ukraine?',
    choices: ['Hoverla', 'Elbrus', 'Gerlach', 'Musala'], correct: 0 },
  { id: 'ua-10', category: 'Ukraine', difficulty: 'easy',
    text: 'Varenyky are Ukrainian dumplings often filled with potato or which fruit?',
    choices: ['Sour cherries', 'Bananas', 'Oranges', 'Kiwi'], correct: 0 },
  { id: 'ua-11', category: 'Ukraine', difficulty: 'medium',
    text: 'What is the Ukrainian dish holubtsi?',
    choices: ['Stuffed cabbage rolls', 'A fish soup', 'A honey cake', 'Fried cheese pancakes'], correct: 0 },
  { id: 'ua-12', category: 'Ukraine', difficulty: 'medium',
    text: 'Which many-stringed instrument is a national symbol of Ukrainian folk music?',
    choices: ['Bandura', 'Balalaika', 'Sitar', 'Banjo'], correct: 0 },
  { id: 'ua-13', category: 'Ukraine', difficulty: 'medium',
    text: 'Kutia, a traditional Ukrainian Christmas dish, is made from wheat, honey and what else?',
    choices: ['Poppy seeds', 'Minced beef', 'Pickled herring', 'Melted cheese'], correct: 0 },
  { id: 'ua-14', category: 'Ukraine', difficulty: 'medium',
    text: 'According to legend, Kyiv was founded by three brothers and their sister. What was the eldest brother’s name?',
    choices: ['Kyi', 'Bohdan', 'Taras', 'Danylo'], correct: 0 },
  { id: 'ua-15', category: 'Ukraine', difficulty: 'easy',
    text: 'In which year did the Chornobyl nuclear disaster occur?',
    choices: ['1986', '1979', '1991', '1968'], correct: 0 },
  { id: 'ua-16', category: 'Ukraine', difficulty: 'medium',
    text: 'The famous Potemkin Stairs are a landmark of which Ukrainian city?',
    choices: ['Odesa', 'Kyiv', 'Chernihiv', 'Uzhhorod'], correct: 0 },
  { id: 'ua-17', category: 'Ukraine', difficulty: 'medium',
    text: 'Which Ukrainian poet wrote the celebrated collection “Kobzar”?',
    choices: ['Taras Shevchenko', 'Ivan Franko', 'Lesya Ukrainka', 'Hryhorii Skovoroda'], correct: 0 },
  { id: 'ua-18', category: 'Ukraine', difficulty: 'medium',
    text: 'What are pysanky?',
    choices: ['Decorated Easter eggs', 'Embroidered towels', 'Clay whistles', 'Woven belts'], correct: 0 },
  { id: 'ua-19', category: 'Ukraine', difficulty: 'easy',
    text: 'Which of these countries shares a border with Ukraine?',
    choices: ['Poland', 'Lithuania', 'Bulgaria', 'Latvia'], correct: 0 },
  { id: 'ua-20', category: 'Ukraine', difficulty: 'easy',
    text: 'Salo, a beloved Ukrainian delicacy, is made from what?',
    choices: ['Cured pork fat', 'Smoked salmon', 'Goat cheese', 'Dried mushrooms'], correct: 0 },

  // ── Czech Republic (20) ─────────────────────────────────────────
  { id: 'cz-01', category: 'Czech Republic', difficulty: 'easy',
    text: 'What is the capital of the Czech Republic?',
    choices: ['Prague', 'Brno', 'Ostrava', 'Plzeň'], correct: 0 },
  { id: 'cz-02', category: 'Czech Republic', difficulty: 'easy',
    text: 'Which famous medieval bridge crosses the Vltava river in Prague?',
    choices: ['Charles Bridge', 'Tower Bridge', 'Rialto Bridge', 'Chain Bridge'], correct: 0 },
  { id: 'cz-03', category: 'Czech Republic', difficulty: 'easy',
    text: 'Pilsner Urquell, the original pale lager, comes from which Czech city?',
    choices: ['Plzeň', 'Olomouc', 'Liberec', 'Karlovy Vary'], correct: 0 },
  { id: 'cz-04', category: 'Czech Republic', difficulty: 'easy',
    text: 'Škoda, one of the world’s oldest car makers, is from which country?',
    choices: ['Czech Republic', 'Germany', 'Sweden', 'France'], correct: 0 },
  { id: 'cz-05', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which playwright and former dissident became the first president of the Czech Republic?',
    choices: ['Václav Havel', 'Václav Klaus', 'Alexander Dubček', 'Miloš Zeman'], correct: 0 },
  { id: 'cz-06', category: 'Czech Republic', difficulty: 'easy',
    text: 'Krtek, the beloved Czech cartoon character, is what kind of animal?',
    choices: ['A mole', 'A hedgehog', 'A rabbit', 'A badger'], correct: 0 },
  { id: 'cz-07', category: 'Czech Republic', difficulty: 'medium',
    text: 'Charles IV, King of Bohemia and Holy Roman Emperor, founded what in Prague in 1348?',
    choices: ['A university', 'An opera house', 'A brewery', 'A zoo'], correct: 0 },
  { id: 'cz-08', category: 'Czech Republic', difficulty: 'easy',
    text: 'What is the currency of the Czech Republic?',
    choices: ['Czech koruna', 'Euro', 'Forint', 'Franc'], correct: 0 },
  { id: 'cz-09', category: 'Czech Republic', difficulty: 'medium',
    text: 'What is the Orloj, a famous attraction on Prague’s Old Town Square?',
    choices: ['A medieval astronomical clock', 'A golden fountain', 'A marionette theatre', 'A bell tower organ'], correct: 0 },
  { id: 'cz-10', category: 'Czech Republic', difficulty: 'medium',
    text: 'In which sport did the Czech Republic win Olympic gold at Nagano 1998, sparking national celebrations?',
    choices: ['Ice hockey', 'Football', 'Basketball', 'Volleyball'], correct: 0 },
  { id: 'cz-11', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which Czech composer wrote “Vltava”, part of the cycle “Má vlast” (My Homeland)?',
    choices: ['Bedřich Smetana', 'Antonín Dvořák', 'Leoš Janáček', 'Bohuslav Martinů'], correct: 0 },
  { id: 'cz-12', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which Czech composer wrote the “New World Symphony” while living in America?',
    choices: ['Antonín Dvořák', 'Bedřich Smetana', 'Franz Liszt', 'Gustav Mahler'], correct: 0 },
  { id: 'cz-13', category: 'Czech Republic', difficulty: 'easy',
    text: 'Which author of “The Metamorphosis” was born in Prague in 1883?',
    choices: ['Franz Kafka', 'Milan Kundera', 'Stefan Zweig', 'Hermann Hesse'], correct: 0 },
  { id: 'cz-14', category: 'Czech Republic', difficulty: 'medium',
    text: 'The word “robot” was introduced to the world in a 1920 play by which Czech writer?',
    choices: ['Karel Čapek', 'Jaroslav Hašek', 'Božena Němcová', 'Franz Kafka'], correct: 0 },
  { id: 'cz-15', category: 'Czech Republic', difficulty: 'easy',
    text: 'What is the name of the historical region in the eastern part of the Czech Republic?',
    choices: ['Moravia', 'Bavaria', 'Silesia Major', 'Galicia'], correct: 0 },
  { id: 'cz-16', category: 'Czech Republic', difficulty: 'medium',
    text: 'In which year did Czechoslovakia peacefully split into the Czech Republic and Slovakia?',
    choices: ['1993', '1989', '1997', '1985'], correct: 0 },
  { id: 'cz-17', category: 'Czech Republic', difficulty: 'easy',
    text: 'The classic Czech dish “vepřo knedlo zelo” consists of roast pork, cabbage and what else?',
    choices: ['Bread dumplings', 'French fries', 'Rice', 'Spaghetti'], correct: 0 },
  { id: 'cz-18', category: 'Czech Republic', difficulty: 'medium',
    text: 'Prague Castle holds a Guinness World Record as the largest what?',
    choices: ['Ancient castle complex', 'Wooden building', 'Underground labyrinth', 'Royal garden'], correct: 0 },
  { id: 'cz-19', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which Czech town is world-famous for its hot springs and spa colonnades?',
    choices: ['Karlovy Vary', 'Kutná Hora', 'Telč', 'České Budějovice'], correct: 0 },
  { id: 'cz-20', category: 'Czech Republic', difficulty: 'easy',
    text: 'The Czech Republic has long held the world record in the per-capita consumption of what?',
    choices: ['Beer', 'Coffee', 'Chocolate', 'Ice cream'], correct: 0 },

  // ── Video games (20) ────────────────────────────────────────────
  { id: 'vg-01', category: 'Video games', difficulty: 'easy',
    text: 'In which country was Tetris created in 1984?',
    choices: ['Soviet Union', 'Japan', 'United States', 'Germany'], correct: 0 },
  { id: 'vg-02', category: 'Video games', difficulty: 'easy',
    text: 'What is the profession of Nintendo’s mascot Mario?',
    choices: ['Plumber', 'Carpenter', 'Chef', 'Firefighter'], correct: 0 },
  { id: 'vg-03', category: 'Video games', difficulty: 'easy',
    text: 'What is the name of Mario’s taller, green-clad brother?',
    choices: ['Luigi', 'Wario', 'Yoshi', 'Toad'], correct: 0 },
  { id: 'vg-04', category: 'Video games', difficulty: 'easy',
    text: 'What is the name of the hero you play in “The Legend of Zelda” games?',
    choices: ['Link', 'Zelda', 'Ganon', 'Epona'], correct: 0 },
  { id: 'vg-05', category: 'Video games', difficulty: 'easy',
    text: 'Which studio originally created Minecraft?',
    choices: ['Mojang', 'Ubisoft', 'Valve', 'Blizzard'], correct: 0 },
  { id: 'vg-06', category: 'Video games', difficulty: 'medium',
    text: 'The Witcher games are based on books by an author from which country?',
    choices: ['Poland', 'Russia', 'Czech Republic', 'Hungary'], correct: 0 },
  { id: 'vg-07', category: 'Video games', difficulty: 'easy',
    text: 'What is the name of the monster-slaying protagonist of The Witcher series?',
    choices: ['Geralt of Rivia', 'Ezio Auditore', 'Arthas Menethil', 'Triss Merigold'], correct: 0 },
  { id: 'vg-08', category: 'Video games', difficulty: 'medium',
    text: 'The game Kingdom Come: Deliverance is set in the medieval kingdom of…',
    choices: ['Bohemia', 'Burgundy', 'Castile', 'Wessex'], correct: 0 },
  { id: 'vg-09', category: 'Video games', difficulty: 'medium',
    text: 'Which studio created the pioneering shooter Doom in 1993?',
    choices: ['id Software', 'Epic Games', 'Rockstar', 'Naughty Dog'], correct: 0 },
  { id: 'vg-10', category: 'Video games', difficulty: 'easy',
    text: 'Pac-Man, the dot-munching arcade classic, was originally released by a company from which country?',
    choices: ['Japan', 'United States', 'South Korea', 'Italy'], correct: 0 },
  { id: 'vg-11', category: 'Video games', difficulty: 'easy',
    text: 'Sega’s speedy blue mascot Sonic is what kind of animal?',
    choices: ['Hedgehog', 'Fox', 'Armadillo', 'Porcupine'], correct: 0 },
  { id: 'vg-12', category: 'Video games', difficulty: 'easy',
    text: 'In Pokémon, what type is Pikachu?',
    choices: ['Electric', 'Fire', 'Water', 'Grass'], correct: 0 },
  { id: 'vg-13', category: 'Video games', difficulty: 'easy',
    text: 'What does GTA stand for in the famous game series?',
    choices: ['Grand Theft Auto', 'Great Tank Assault', 'Global Tactical Army', 'Grand Turbo Arena'], correct: 0 },
  { id: 'vg-14', category: 'Video games', difficulty: 'easy',
    text: 'Which hybrid home/portable console did Nintendo release in 2017?',
    choices: ['Switch', 'Wii U', 'GameCube', 'Dreamcast'], correct: 0 },
  { id: 'vg-15', category: 'Video games', difficulty: 'medium',
    text: 'In the game Portal, which reward is famously promised — and famously “a lie”?',
    choices: ['Cake', 'Pizza', 'A gold medal', 'A vacation'], correct: 0 },
  { id: 'vg-16', category: 'Video games', difficulty: 'easy',
    text: 'Which company created Fortnite?',
    choices: ['Epic Games', 'Activision', 'EA', 'Riot Games'], correct: 0 },
  { id: 'vg-17', category: 'Video games', difficulty: 'medium',
    text: 'Master Chief is the armored hero of which game series?',
    choices: ['Halo', 'Gears of War', 'Destiny', 'Mass Effect'], correct: 0 },
  { id: 'vg-18', category: 'Video games', difficulty: 'easy',
    text: 'Lara Croft is the adventuring star of which game series?',
    choices: ['Tomb Raider', 'Uncharted', 'Far Cry', 'Resident Evil'], correct: 0 },
  { id: 'vg-19', category: 'Video games', difficulty: 'medium',
    text: 'Kingdom Come: Deliverance was developed by Warhorse Studios, based in which city?',
    choices: ['Prague', 'Warsaw', 'Berlin', 'Vienna'], correct: 0 },
  { id: 'vg-20', category: 'Video games', difficulty: 'medium',
    text: 'Rovio, the company behind Angry Birds, comes from which country?',
    choices: ['Finland', 'Japan', 'Canada', 'Ireland'], correct: 0 },

  // ── Movies & TV (25) ────────────────────────────────────────────
  { id: 'mv-01', category: 'Movies & TV', difficulty: 'easy',
    text: 'Who directed the 1997 blockbuster Titanic?',
    choices: ['James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Peter Jackson'], correct: 0 },
  { id: 'mv-02', category: 'Movies & TV', difficulty: 'easy',
    text: '“May the Force be with you” is a famous line from which film saga?',
    choices: ['Star Wars', 'Star Trek', 'Dune', 'The Matrix'], correct: 0 },
  { id: 'mv-03', category: 'Movies & TV', difficulty: 'easy',
    text: 'In the sitcom Friends, what is the name of the coffee shop where the gang hangs out?',
    choices: ['Central Perk', 'The Daily Grind', 'Java Joe’s', 'MacLaren’s'], correct: 0 },
  { id: 'mv-04', category: 'Movies & TV', difficulty: 'easy',
    text: 'What is the name of the school for wizards in Harry Potter?',
    choices: ['Hogwarts', 'Durmstrang', 'Narnia', 'Rivendell'], correct: 0 },
  { id: 'mv-05', category: 'Movies & TV', difficulty: 'easy',
    text: 'In which town do The Simpsons live?',
    choices: ['Springfield', 'Quahog', 'South Park', 'Bedrock'], correct: 0 },
  { id: 'mv-06', category: 'Movies & TV', difficulty: 'easy',
    text: 'Who directed Jurassic Park (1993)?',
    choices: ['Steven Spielberg', 'George Lucas', 'Tim Burton', 'Christopher Nolan'], correct: 0 },
  { id: 'mv-07', category: 'Movies & TV', difficulty: 'easy',
    text: 'In The Matrix, which pill does Neo take to learn the truth?',
    choices: ['The red pill', 'The blue pill', 'The green pill', 'The white pill'], correct: 0 },
  { id: 'mv-08', category: 'Movies & TV', difficulty: 'easy',
    text: 'Toy Story (1995) was the first feature film made by which animation studio?',
    choices: ['Pixar', 'DreamWorks', 'Studio Ghibli', 'Illumination'], correct: 0 },
  { id: 'mv-09', category: 'Movies & TV', difficulty: 'easy',
    text: 'In Breaking Bad, what subject does Walter White teach before turning to crime?',
    choices: ['Chemistry', 'Physics', 'Mathematics', 'History'], correct: 0 },
  { id: 'mv-10', category: 'Movies & TV', difficulty: 'easy',
    text: 'Game of Thrones is based on novels by which author?',
    choices: ['George R. R. Martin', 'J. R. R. Tolkien', 'Stephen King', 'C. S. Lewis'], correct: 0 },
  { id: 'mv-11', category: 'Movies & TV', difficulty: 'easy',
    text: 'Who played the title role in Forrest Gump?',
    choices: ['Tom Hanks', 'Brad Pitt', 'Kevin Costner', 'Robin Williams'], correct: 0 },
  { id: 'mv-12', category: 'Movies & TV', difficulty: 'easy',
    text: 'What is the name of the villainous uncle in The Lion King?',
    choices: ['Scar', 'Mufasa', 'Timon', 'Rafiki'], correct: 0 },
  { id: 'mv-13', category: 'Movies & TV', difficulty: 'easy',
    text: 'In The Lord of the Rings, where must the One Ring be destroyed?',
    choices: ['Mount Doom', 'Helm’s Deep', 'Minas Tirith', 'The Shire'], correct: 0 },
  { id: 'mv-14', category: 'Movies & TV', difficulty: 'easy',
    text: 'What kind of creature is Shrek?',
    choices: ['An ogre', 'A troll', 'A giant', 'A goblin'], correct: 0 },
  { id: 'mv-15', category: 'Movies & TV', difficulty: 'medium',
    text: 'In Stranger Things, what is the sinister parallel dimension called?',
    choices: ['The Upside Down', 'The Nether', 'The Shadowlands', 'The Void'], correct: 0 },
  { id: 'mv-16', category: 'Movies & TV', difficulty: 'medium',
    text: 'In the US version of The Office, what does Dunder Mifflin sell?',
    choices: ['Paper', 'Insurance', 'Furniture', 'Printers only'], correct: 0 },
  { id: 'mv-17', category: 'Movies & TV', difficulty: 'easy',
    text: 'Which song does Elsa sing as she builds her ice palace in Frozen?',
    choices: ['Let It Go', 'Into the Unknown', 'A Whole New World', 'Under the Sea'], correct: 0 },
  { id: 'mv-18', category: 'Movies & TV', difficulty: 'medium',
    text: 'Who directed Pulp Fiction (1994)?',
    choices: ['Quentin Tarantino', 'Martin Scorsese', 'David Fincher', 'Guy Ritchie'], correct: 0 },
  { id: 'mv-19', category: 'Movies & TV', difficulty: 'easy',
    text: 'Which actor delivers the famous line “I’ll be back” in The Terminator?',
    choices: ['Arnold Schwarzenegger', 'Sylvester Stallone', 'Bruce Willis', 'Jean-Claude Van Damme'], correct: 0 },
  { id: 'mv-20', category: 'Movies & TV', difficulty: 'medium',
    text: 'In James Cameron’s Avatar (2009), what is the name of the alien moon where the story takes place?',
    choices: ['Pandora', 'Krypton', 'Arrakis', 'Endor'], correct: 0 },
  { id: 'mv-21', category: 'Movies & TV', difficulty: 'medium',
    text: 'At which London address does Sherlock Holmes famously live?',
    choices: ['221B Baker Street', '10 Downing Street', '4 Privet Drive', '42 Wallaby Way'], correct: 0 },
  { id: 'mv-22', category: 'Movies & TV', difficulty: 'easy',
    text: 'In The Big Bang Theory, which character is known for the catchphrase “Bazinga!”?',
    choices: ['Sheldon', 'Leonard', 'Howard', 'Raj'], correct: 0 },
  { id: 'mv-23', category: 'Movies & TV', difficulty: 'easy',
    text: 'In Finding Nemo, what kind of fish are Nemo and his dad Marlin?',
    choices: ['Clownfish', 'Angelfish', 'Swordfish', 'Pufferfish'], correct: 0 },
  { id: 'mv-24', category: 'Movies & TV', difficulty: 'medium',
    text: 'Which car is turned into a time machine in Back to the Future?',
    choices: ['DeLorean', 'Ford Mustang', 'Volkswagen Beetle', 'Chevrolet Camaro'], correct: 0 },
  { id: 'mv-25', category: 'Movies & TV', difficulty: 'easy',
    text: 'What is the first name of the boy left behind in Home Alone?',
    choices: ['Kevin', 'Michael', 'Timmy', 'Josh'], correct: 0 },

  // ── Fun facts (20) ──────────────────────────────────────────────
  { id: 'ff-01', category: 'Fun facts', difficulty: 'medium',
    text: 'How many hearts does an octopus have?',
    choices: ['Three', 'One', 'Two', 'Five'], correct: 0 },
  { id: 'ff-02', category: 'Fun facts', difficulty: 'easy',
    text: 'Which food never spoils when stored properly — edible even after thousands of years?',
    choices: ['Honey', 'Milk', 'Bread', 'Cheese'], correct: 0 },
  { id: 'ff-03', category: 'Fun facts', difficulty: 'medium',
    text: 'How many bones are in the adult human body?',
    choices: ['206', '186', '250', '300'], correct: 0 },
  { id: 'ff-04', category: 'Fun facts', difficulty: 'easy',
    text: 'What is the fastest land animal?',
    choices: ['Cheetah', 'Lion', 'Pronghorn', 'Greyhound'], correct: 0 },
  { id: 'ff-05', category: 'Fun facts', difficulty: 'easy',
    text: 'What is the largest animal ever known to have lived on Earth?',
    choices: ['Blue whale', 'African elephant', 'Tyrannosaurus rex', 'Giant squid'], correct: 0 },
  { id: 'ff-06', category: 'Fun facts', difficulty: 'medium',
    text: 'Botanically speaking, the banana plant is classified as what?',
    choices: ['An herb', 'A tree', 'A shrub', 'A vine'], correct: 0 },
  { id: 'ff-07', category: 'Fun facts', difficulty: 'easy',
    text: 'What is a group of lions called?',
    choices: ['A pride', 'A pack', 'A herd', 'A flock'], correct: 0 },
  { id: 'ff-08', category: 'Fun facts', difficulty: 'medium',
    text: 'Which animal can sleep for up to 22 hours a day?',
    choices: ['Koala', 'Horse', 'Dolphin', 'Cheetah'], correct: 0 },
  { id: 'ff-09', category: 'Fun facts', difficulty: 'medium',
    text: 'Which element makes up the largest share of the human body by mass?',
    choices: ['Oxygen', 'Carbon', 'Iron', 'Calcium'], correct: 0 },
  { id: 'ff-10', category: 'Fun facts', difficulty: 'medium',
    text: 'The shortest war in recorded history, between Britain and Zanzibar in 1896, lasted roughly how long?',
    choices: ['40 minutes', '4 hours', '4 days', '4 weeks'], correct: 0 },
  { id: 'ff-11', category: 'Fun facts', difficulty: 'easy',
    text: 'Which bird lays the largest egg of any living animal?',
    choices: ['Ostrich', 'Emu', 'Albatross', 'Swan'], correct: 0 },
  { id: 'ff-12', category: 'Fun facts', difficulty: 'medium',
    text: 'Before the 17th century, most cultivated carrots were what colour?',
    choices: ['Purple', 'Orange', 'Blue', 'Pink'], correct: 0 },
  { id: 'ff-13', category: 'Fun facts', difficulty: 'medium',
    text: 'What is a group of cats called?',
    choices: ['A clowder', 'A litter', 'A colony wave', 'A purr'], correct: 0 },
  { id: 'ff-14', category: 'Fun facts', difficulty: 'easy',
    text: 'What is the only mammal capable of true, sustained flight?',
    choices: ['Bat', 'Flying squirrel', 'Sugar glider', 'Colugo'], correct: 0 },
  { id: 'ff-15', category: 'Fun facts', difficulty: 'easy',
    text: 'Which fruit wears its seeds on the outside?',
    choices: ['Strawberry', 'Raspberry', 'Blueberry', 'Grape'], correct: 0 },
  { id: 'ff-16', category: 'Fun facts', difficulty: 'medium',
    text: 'The spiciness of chili peppers is measured on which scale?',
    choices: ['Scoville scale', 'Richter scale', 'Beaufort scale', 'Mohs scale'], correct: 0 },
  { id: 'ff-17', category: 'Fun facts', difficulty: 'easy',
    text: 'In which hemisphere do nearly all wild penguins live?',
    choices: ['Southern', 'Northern', 'Both equally', 'Only at the equator'], correct: 0 },
  { id: 'ff-18', category: 'Fun facts', difficulty: 'easy',
    text: 'How many teeth does an adult human typically have, including wisdom teeth?',
    choices: ['32', '28', '36', '24'], correct: 0 },
  { id: 'ff-19', category: 'Fun facts', difficulty: 'medium',
    text: 'How many neck vertebrae does a giraffe have?',
    choices: ['Seven — the same as humans', 'Fourteen', 'Twenty-one', 'Three'], correct: 0 },
  { id: 'ff-20', category: 'Fun facts', difficulty: 'easy',
    text: 'Which animal is famously the slowest-moving mammal on Earth?',
    choices: ['Three-toed sloth', 'Tortoise', 'Snail', 'Koala'], correct: 0 },

  // ── Science & space (15) ────────────────────────────────────────
  { id: 'sc-01', category: 'Science & space', difficulty: 'easy',
    text: 'Which planet is known as the Red Planet?',
    choices: ['Mars', 'Venus', 'Jupiter', 'Mercury'], correct: 0 },
  { id: 'sc-02', category: 'Science & space', difficulty: 'easy',
    text: 'What is the largest planet in our solar system?',
    choices: ['Jupiter', 'Saturn', 'Neptune', 'Earth'], correct: 0 },
  { id: 'sc-03', category: 'Science & space', difficulty: 'easy',
    text: 'Which element has the chemical symbol O?',
    choices: ['Oxygen', 'Osmium', 'Gold', 'Oxide'], correct: 0 },
  { id: 'sc-04', category: 'Science & space', difficulty: 'easy',
    text: 'H₂O is the chemical formula for what?',
    choices: ['Water', 'Hydrogen peroxide', 'Salt', 'Ozone'], correct: 0 },
  { id: 'sc-05', category: 'Science & space', difficulty: 'easy',
    text: 'Who was the first human to travel into space, in 1961?',
    choices: ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn'], correct: 0 },
  { id: 'sc-06', category: 'Science & space', difficulty: 'easy',
    text: 'Who was the first person to walk on the Moon?',
    choices: ['Neil Armstrong', 'Yuri Gagarin', 'Michael Collins', 'Alan Shepard'], correct: 0 },
  { id: 'sc-07', category: 'Science & space', difficulty: 'medium',
    text: 'What is the approximate speed of light in a vacuum?',
    choices: ['300,000 km per second', '30,000 km per second', '3,000 km per second', '3 million km per second'], correct: 0 },
  { id: 'sc-08', category: 'Science & space', difficulty: 'easy',
    text: 'Which planet is famous for its spectacular ring system?',
    choices: ['Saturn', 'Mars', 'Mercury', 'Venus'], correct: 0 },
  { id: 'sc-09', category: 'Science & space', difficulty: 'medium',
    text: 'Who discovered penicillin in 1928?',
    choices: ['Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Robert Koch'], correct: 0 },
  { id: 'sc-10', category: 'Science & space', difficulty: 'easy',
    text: 'Who developed the theory of relativity?',
    choices: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Stephen Hawking'], correct: 0 },
  { id: 'sc-11', category: 'Science & space', difficulty: 'medium',
    text: 'Which element has the chemical symbol Au?',
    choices: ['Gold', 'Silver', 'Aluminium', 'Argon'], correct: 0 },
  { id: 'sc-12', category: 'Science & space', difficulty: 'easy',
    text: 'What is the closest star to Earth?',
    choices: ['The Sun', 'Proxima Centauri', 'Sirius', 'Polaris'], correct: 0 },
  { id: 'sc-13', category: 'Science & space', difficulty: 'easy',
    text: 'How many planets are in our solar system?',
    choices: ['Eight', 'Nine', 'Seven', 'Ten'], correct: 0 },
  { id: 'sc-14', category: 'Science & space', difficulty: 'medium',
    text: 'Marie Curie won Nobel Prizes in which two sciences?',
    choices: ['Physics and Chemistry', 'Physics and Medicine', 'Chemistry and Medicine', 'Physics and Literature'], correct: 0 },
  { id: 'sc-15', category: 'Science & space', difficulty: 'easy',
    text: 'What shape is the DNA molecule?',
    choices: ['Double helix', 'Single ring', 'Flat sheet', 'Triple knot'], correct: 0 },
  { id: 'sc-16', category: 'Science & space', difficulty: 'medium',
    text: 'What is the most abundant element in the universe?',
    choices: ['Hydrogen', 'Oxygen', 'Helium', 'Carbon'], correct: 0 },
  { id: 'sc-17', category: 'Science & space', difficulty: 'medium',
    text: 'Roughly how long does sunlight take to reach Earth?',
    choices: ['8 minutes', '8 seconds', '8 hours', '8 days'], correct: 0 },
  { id: 'sc-18', category: 'Science & space', difficulty: 'hard',
    text: 'Which long-sought particle did CERN confirm in 2012?',
    choices: ['Higgs boson', 'Graviton', 'Tachyon', 'Neutrino'], correct: 0 },
  { id: 'sc-19', category: 'Science & space', difficulty: 'hard',
    text: 'What is absolute zero, the coldest possible temperature, in Celsius?',
    choices: ['About −273 °C', 'About −100 °C', 'About −500 °C', 'Exactly 0 °C'], correct: 0 },
  { id: 'sc-20', category: 'Science & space', difficulty: 'hard',
    text: 'On which planet does the Sun rise in the west, because it spins backwards?',
    choices: ['Venus', 'Mars', 'Jupiter', 'Mercury'], correct: 0 },

  // ── Ukraine — harder additions ──────────────────────────────────
  { id: 'ua-21', category: 'Ukraine', difficulty: 'hard',
    text: 'What was the powerful medieval East Slavic state centered on Kyiv called?',
    choices: ['Kyivan Rus', 'The Golden Horde', 'Great Moravia', 'The Hanseatic League'], correct: 0 },
  { id: 'ua-22', category: 'Ukraine', difficulty: 'hard',
    text: 'Which hetman led the great Cossack uprising that began in 1648?',
    choices: ['Bohdan Khmelnytsky', 'Ivan Mazepa', 'Petro Sahaidachny', 'Pylyp Orlyk'], correct: 0 },
  { id: 'ua-23', category: 'Ukraine', difficulty: 'medium',
    text: 'In which year did Ukraine declare independence?',
    choices: ['1991', '1989', '1993', '1985'], correct: 0 },
  { id: 'ua-24', category: 'Ukraine', difficulty: 'hard',
    text: 'During which traditional midsummer festival do Ukrainians jump over bonfires?',
    choices: ['Ivana Kupala', 'Malanka', 'Obzhynky', 'Vertep'], correct: 0 },

  // ── Czech Republic — harder additions ───────────────────────────
  { id: 'cz-21', category: 'Czech Republic', difficulty: 'hard',
    text: 'In which year was the Czech reformer Jan Hus burned at the stake?',
    choices: ['1415', '1348', '1526', '1620'], correct: 0 },
  { id: 'cz-22', category: 'Czech Republic', difficulty: 'hard',
    text: 'Which Czech film directed by Jiří Menzel won the Oscar for Best Foreign Language Film in 1968?',
    choices: ['Closely Watched Trains', 'Kolya', 'The Firemen’s Ball', 'Loves of a Blonde'], correct: 0 },
  { id: 'cz-23', category: 'Czech Republic', difficulty: 'hard',
    text: 'Villa Tugendhat, a UNESCO-listed functionalist masterpiece, stands in which Czech city?',
    choices: ['Brno', 'Prague', 'Ostrava', 'Zlín'], correct: 0 },
  { id: 'cz-24', category: 'Czech Republic', difficulty: 'medium',
    text: 'Which Czech-born tennis player won a record nine Wimbledon singles titles?',
    choices: ['Martina Navrátilová', 'Petra Kvitová', 'Ivan Lendl', 'Jana Novotná'], correct: 0 },

  // ── Video games — harder additions ──────────────────────────────
  { id: 'vg-21', category: 'Video games', difficulty: 'hard',
    text: 'Who composed the iconic Super Mario Bros. theme?',
    choices: ['Koji Kondo', 'Nobuo Uematsu', 'Shigeru Miyamoto', 'Yoko Shimomura'], correct: 0 },
  { id: 'vg-22', category: 'Video games', difficulty: 'hard',
    text: 'What did Nintendo originally make when it was founded back in 1889?',
    choices: ['Playing cards', 'Typewriters', 'Bicycles', 'Radios'], correct: 0 },
  { id: 'vg-23', category: 'Video games', difficulty: 'medium',
    text: 'In Tetris, what is it called when you clear four lines at once?',
    choices: ['A Tetris', 'A Quad', 'A Combo', 'A Blockbuster'], correct: 0 },
  { id: 'vg-24', category: 'Video games', difficulty: 'medium',
    text: 'Cloud Strife is the spiky-haired hero of which 1997 RPG classic?',
    choices: ['Final Fantasy VII', 'Chrono Trigger', 'Secret of Mana', 'Baldur’s Gate'], correct: 0 },
  { id: 'vg-25', category: 'Video games', difficulty: 'medium',
    text: 'StarCraft became a national esports phenomenon in which country?',
    choices: ['South Korea', 'Japan', 'Sweden', 'Brazil'], correct: 0 },

  // ── Movies & TV — harder additions ──────────────────────────────
  { id: 'mv-26', category: 'Movies & TV', difficulty: 'hard',
    text: 'Which film won the very first Academy Award for Best Picture?',
    choices: ['Wings', 'Metropolis', 'Gone with the Wind', 'The Jazz Singer'], correct: 0 },
  { id: 'mv-27', category: 'Movies & TV', difficulty: 'hard',
    text: 'Czech-born director Miloš Forman won Best Director Oscars for Amadeus and which other film?',
    choices: ['One Flew Over the Cuckoo’s Nest', 'Taxi Driver', 'The Deer Hunter', 'Apocalypse Now'], correct: 0 },
  { id: 'mv-28', category: 'Movies & TV', difficulty: 'hard',
    text: 'What is the name of the precious mineral mined on Pandora in Avatar?',
    choices: ['Unobtanium', 'Vibranium', 'Adamantium', 'Kryptonite'], correct: 0 },
  { id: 'mv-29', category: 'Movies & TV', difficulty: 'medium',
    text: 'Hayao Miyazaki, director of Spirited Away, co-founded which animation studio?',
    choices: ['Studio Ghibli', 'Toei Animation', 'Madhouse', 'Kyoto Animation'], correct: 0 },

  // ── Fun facts — harder additions ────────────────────────────────
  { id: 'ff-21', category: 'Fun facts', difficulty: 'medium',
    text: 'Roughly what percentage of the adult human body is water?',
    choices: ['About 60%', 'About 30%', 'About 90%', 'About 45%'], correct: 0 },
  { id: 'ff-22', category: 'Fun facts', difficulty: 'hard',
    text: 'What colour is an octopus’s blood?',
    choices: ['Blue', 'Red', 'Green', 'Clear'], correct: 0 },
  { id: 'ff-23', category: 'Fun facts', difficulty: 'hard',
    text: 'Which animal produces the loudest sound on Earth?',
    choices: ['Sperm whale', 'African elephant', 'Howler monkey', 'Lion'], correct: 0 },

  // ── Music (15) ──────────────────────────────────────────────────
  { id: 'mu-01', category: 'Music', difficulty: 'easy',
    text: 'Which band recorded the six-minute epic “Bohemian Rhapsody”?',
    choices: ['Queen', 'The Beatles', 'Led Zeppelin', 'Pink Floyd'], correct: 0 },
  { id: 'mu-02', category: 'Music', difficulty: 'easy',
    text: 'Who is known as the “King of Pop”?',
    choices: ['Michael Jackson', 'Elvis Presley', 'Prince', 'Freddie Mercury'], correct: 0 },
  { id: 'mu-03', category: 'Music', difficulty: 'easy',
    text: 'ABBA, the group behind “Dancing Queen”, comes from which country?',
    choices: ['Sweden', 'Norway', 'Germany', 'United Kingdom'], correct: 0 },
  { id: 'mu-04', category: 'Music', difficulty: 'easy',
    text: 'The Beatles formed in which English city?',
    choices: ['Liverpool', 'London', 'Manchester', 'Birmingham'], correct: 0 },
  { id: 'mu-05', category: 'Music', difficulty: 'easy',
    text: 'How many keys does a standard piano have?',
    choices: ['88', '66', '100', '76'], correct: 0 },
  { id: 'mu-06', category: 'Music', difficulty: 'medium',
    text: 'Which band opened the 90s grunge era with “Smells Like Teen Spirit”?',
    choices: ['Nirvana', 'Pearl Jam', 'Radiohead', 'Metallica'], correct: 0 },
  { id: 'mu-07', category: 'Music', difficulty: 'medium',
    text: 'The helmeted electronic duo Daft Punk came from which country?',
    choices: ['France', 'Germany', 'United States', 'Netherlands'], correct: 0 },
  { id: 'mu-08', category: 'Music', difficulty: 'easy',
    text: 'Who sang the hits “Rolling in the Deep” and “Hello”?',
    choices: ['Adele', 'Beyoncé', 'Rihanna', 'Lady Gaga'], correct: 0 },
  { id: 'mu-09', category: 'Music', difficulty: 'easy',
    text: 'Bob Marley made which music genre world-famous?',
    choices: ['Reggae', 'Jazz', 'Blues', 'Ska-punk'], correct: 0 },
  { id: 'mu-10', category: 'Music', difficulty: 'medium',
    text: 'How many strings does a standard violin have?',
    choices: ['Four', 'Six', 'Five', 'Eight'], correct: 0 },
  { id: 'mu-11', category: 'Music', difficulty: 'medium',
    text: 'Which composer kept writing masterpieces even after losing his hearing?',
    choices: ['Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Frédéric Chopin'], correct: 0 },
  { id: 'mu-12', category: 'Music', difficulty: 'hard',
    text: 'Queen frontman Freddie Mercury was born on which island?',
    choices: ['Zanzibar', 'Malta', 'Cyprus', 'Madagascar'], correct: 0 },
  { id: 'mu-13', category: 'Music', difficulty: 'medium',
    text: 'Vivaldi’s “The Four Seasons” is a set of concertos for which instrument?',
    choices: ['Violin', 'Piano', 'Flute', 'Cello'], correct: 0 },
  { id: 'mu-14', category: 'Music', difficulty: 'medium',
    text: 'What is the name of Elvis Presley’s famous Memphis mansion?',
    choices: ['Graceland', 'Neverland', 'Dollywood', 'Sun Manor'], correct: 0 },
  { id: 'mu-15', category: 'Music', difficulty: 'hard',
    text: 'Which composer wrote “Ride of the Valkyries”?',
    choices: ['Richard Wagner', 'Giuseppe Verdi', 'Johannes Brahms', 'Franz Schubert'], correct: 0 },

  // ── World geography (15) ────────────────────────────────────────
  { id: 'ge-01', category: 'World geography', difficulty: 'easy',
    text: 'Which river is traditionally considered the longest in the world?',
    choices: ['Nile', 'Amazon', 'Yangtze', 'Mississippi'], correct: 0 },
  { id: 'ge-02', category: 'World geography', difficulty: 'easy',
    text: 'What is the largest ocean on Earth?',
    choices: ['Pacific', 'Atlantic', 'Indian', 'Arctic'], correct: 0 },
  { id: 'ge-03', category: 'World geography', difficulty: 'easy',
    text: 'What is the capital of Japan?',
    choices: ['Tokyo', 'Kyoto', 'Osaka', 'Seoul'], correct: 0 },
  { id: 'ge-04', category: 'World geography', difficulty: 'medium',
    text: 'Which country overtook China in 2023 as the world’s most populous?',
    choices: ['India', 'Indonesia', 'United States', 'Nigeria'], correct: 0 },
  { id: 'ge-05', category: 'World geography', difficulty: 'medium',
    text: 'What is the capital of Australia?',
    choices: ['Canberra', 'Sydney', 'Melbourne', 'Perth'], correct: 0 },
  { id: 'ge-06', category: 'World geography', difficulty: 'medium',
    text: 'What is the capital of Canada?',
    choices: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'], correct: 0 },
  { id: 'ge-07', category: 'World geography', difficulty: 'easy',
    text: 'The Sahara, the largest hot desert on Earth, is on which continent?',
    choices: ['Africa', 'Asia', 'Australia', 'South America'], correct: 0 },
  { id: 'ge-08', category: 'World geography', difficulty: 'medium',
    text: 'Mount Everest sits on the border of Nepal and which other country?',
    choices: ['China', 'India', 'Pakistan', 'Bhutan'], correct: 0 },
  { id: 'ge-09', category: 'World geography', difficulty: 'hard',
    text: 'Counting overseas territories, which country spans the most time zones?',
    choices: ['France', 'Russia', 'United States', 'United Kingdom'], correct: 0 },
  { id: 'ge-10', category: 'World geography', difficulty: 'easy',
    text: 'Which European country is shaped like a boot?',
    choices: ['Italy', 'Spain', 'Greece', 'Portugal'], correct: 0 },
  { id: 'ge-11', category: 'World geography', difficulty: 'medium',
    text: 'What is the capital of New Zealand?',
    choices: ['Wellington', 'Auckland', 'Christchurch', 'Queenstown'], correct: 0 },
  { id: 'ge-12', category: 'World geography', difficulty: 'hard',
    text: 'The Danube river empties into which sea?',
    choices: ['Black Sea', 'Mediterranean Sea', 'Baltic Sea', 'North Sea'], correct: 0 },
  { id: 'ge-13', category: 'World geography', difficulty: 'easy',
    text: 'What is the smallest country in the world?',
    choices: ['Vatican City', 'Monaco', 'Liechtenstein', 'San Marino'], correct: 0 },
  { id: 'ge-14', category: 'World geography', difficulty: 'hard',
    text: 'Which two countries share the longest international border in the world?',
    choices: ['United States and Canada', 'Russia and China', 'Argentina and Chile', 'India and China'], correct: 0 },
  { id: 'ge-15', category: 'World geography', difficulty: 'hard',
    text: 'Which African country famously was never colonized by a European power?',
    choices: ['Ethiopia', 'Kenya', 'Nigeria', 'Ghana'], correct: 0 },

  // ── History (15) ────────────────────────────────────────────────
  { id: 'hi-01', category: 'History', difficulty: 'easy',
    text: 'In which year did World War II end?',
    choices: ['1945', '1939', '1918', '1950'], correct: 0 },
  { id: 'hi-02', category: 'History', difficulty: 'easy',
    text: 'Who was the first president of the United States?',
    choices: ['George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'Benjamin Franklin'], correct: 0 },
  { id: 'hi-03', category: 'History', difficulty: 'medium',
    text: 'In which year did the Titanic sink on its maiden voyage?',
    choices: ['1912', '1905', '1920', '1898'], correct: 0 },
  { id: 'hi-04', category: 'History', difficulty: 'easy',
    text: 'The great pyramids of Egypt were built primarily as what?',
    choices: ['Tombs for pharaohs', 'Grain warehouses', 'Astronomical towers', 'Royal palaces'], correct: 0 },
  { id: 'hi-05', category: 'History', difficulty: 'medium',
    text: 'In which year did the Berlin Wall fall?',
    choices: ['1989', '1991', '1985', '1979'], correct: 0 },
  { id: 'hi-06', category: 'History', difficulty: 'medium',
    text: 'According to legend, which twin founded the city of Rome?',
    choices: ['Romulus', 'Remus', 'Aeneas', 'Julius'], correct: 0 },
  { id: 'hi-07', category: 'History', difficulty: 'hard',
    text: 'The Hundred Years’ War was fought between which two kingdoms?',
    choices: ['England and France', 'Spain and Portugal', 'Austria and Prussia', 'Sweden and Denmark'], correct: 0 },
  { id: 'hi-08', category: 'History', difficulty: 'medium',
    text: 'Who painted the ceiling of the Sistine Chapel?',
    choices: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Botticelli'], correct: 0 },
  { id: 'hi-09', category: 'History', difficulty: 'medium',
    text: 'In which year did the Great Fire of London rage through the city?',
    choices: ['1666', '1606', '1766', '1566'], correct: 0 },
  { id: 'hi-10', category: 'History', difficulty: 'hard',
    text: 'In which year did King John of England seal the Magna Carta?',
    choices: ['1215', '1066', '1315', '1415'], correct: 0 },
  { id: 'hi-11', category: 'History', difficulty: 'medium',
    text: 'At which battle was Napoleon finally defeated in 1815?',
    choices: ['Waterloo', 'Austerlitz', 'Trafalgar', 'Borodino'], correct: 0 },
  { id: 'hi-12', category: 'History', difficulty: 'hard',
    text: 'Which of the Seven Wonders of the Ancient World stood in Alexandria?',
    choices: ['The Lighthouse', 'The Colossus', 'The Hanging Gardens', 'The Temple of Artemis'], correct: 0 },
  { id: 'hi-13', category: 'History', difficulty: 'easy',
    text: 'The Vikings originally came from which region?',
    choices: ['Scandinavia', 'The Mediterranean', 'The British Isles', 'Central Asia'], correct: 0 },
  { id: 'hi-14', category: 'History', difficulty: 'hard',
    text: 'What was the capital of the Byzantine Empire?',
    choices: ['Constantinople', 'Athens', 'Alexandria', 'Antioch'], correct: 0 },
  { id: 'hi-15', category: 'History', difficulty: 'medium',
    text: 'Which civilization built Machu Picchu high in the Andes?',
    choices: ['The Inca', 'The Maya', 'The Aztecs', 'The Olmecs'], correct: 0 },

  // ── Food & drink (15) ───────────────────────────────────────────
  { id: 'fd-01', category: 'Food & drink', difficulty: 'easy',
    text: 'Sushi originally comes from which country?',
    choices: ['Japan', 'China', 'Thailand', 'South Korea'], correct: 0 },
  { id: 'fd-02', category: 'Food & drink', difficulty: 'easy',
    text: 'What is the main ingredient of guacamole?',
    choices: ['Avocado', 'Cucumber', 'Green pepper', 'Peas'], correct: 0 },
  { id: 'fd-03', category: 'Food & drink', difficulty: 'medium',
    text: 'Pizza Margherita is named after an Italian what?',
    choices: ['Queen', 'Volcano', 'Painter', 'Island'], correct: 0 },
  { id: 'fd-04', category: 'Food & drink', difficulty: 'hard',
    text: 'The croissant’s crescent-shaped ancestor, the kipferl, comes from which country?',
    choices: ['Austria', 'France', 'Belgium', 'Switzerland'], correct: 0 },
  { id: 'fd-05', category: 'Food & drink', difficulty: 'easy',
    text: 'Paella is a famous rice dish from which country?',
    choices: ['Spain', 'Italy', 'Mexico', 'Greece'], correct: 0 },
  { id: 'fd-06', category: 'Food & drink', difficulty: 'medium',
    text: 'Wasabi, the green paste served with sushi, is made from what?',
    choices: ['A plant root', 'Ground seaweed', 'Fermented beans', 'Green chili peppers'], correct: 0 },
  { id: 'fd-07', category: 'Food & drink', difficulty: 'medium',
    text: 'After water, what is the most consumed drink in the world?',
    choices: ['Tea', 'Coffee', 'Beer', 'Orange juice'], correct: 0 },
  { id: 'fd-08', category: 'Food & drink', difficulty: 'medium',
    text: 'Real Champagne may only come from a region in which country?',
    choices: ['France', 'Italy', 'Spain', 'Portugal'], correct: 0 },
  { id: 'fd-09', category: 'Food & drink', difficulty: 'hard',
    text: 'What is the most expensive spice in the world by weight?',
    choices: ['Saffron', 'Vanilla', 'Cardamom', 'True cinnamon'], correct: 0 },
  { id: 'fd-10', category: 'Food & drink', difficulty: 'medium',
    text: 'Goulash, the paprika-spiced stew, originates from which country?',
    choices: ['Hungary', 'Poland', 'Germany', 'Romania'], correct: 0 },
  { id: 'fd-11', category: 'Food & drink', difficulty: 'easy',
    text: 'Cheese fondue is a national dish of which country?',
    choices: ['Switzerland', 'Netherlands', 'Denmark', 'Belgium'], correct: 0 },
  { id: 'fd-12', category: 'Food & drink', difficulty: 'hard',
    text: 'The fifth basic taste, umami, was identified by a chemist from which country?',
    choices: ['Japan', 'France', 'Germany', 'United States'], correct: 0 },
  { id: 'fd-13', category: 'Food & drink', difficulty: 'medium',
    text: 'Tequila is distilled from which plant?',
    choices: ['Agave', 'Sugar cane', 'Corn', 'Cactus fruit'], correct: 0 },
  { id: 'fd-14', category: 'Food & drink', difficulty: 'medium',
    text: 'Marzipan is made primarily from sugar and which nut?',
    choices: ['Almonds', 'Hazelnuts', 'Walnuts', 'Pistachios'], correct: 0 },
  { id: 'fd-15', category: 'Food & drink', difficulty: 'easy',
    text: 'What is the main ingredient in hummus?',
    choices: ['Chickpeas', 'Lentils', 'White beans', 'Eggplant'], correct: 0 },
];
